server:
  port: 8084
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

  instance:
    hostname: localhost


spring:
  application:
    name: MoneynMonetaryAuthenticationservice
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: root
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.OracleDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true